version: '3.1'
services:
   database:
      image: postgres
      ports:
         - "5432:5432"
      environment:
         POSTGRES_DB: homestead
         POSTGRES_USER: homestead
         POSTGRES_PASSWORD: secret
