version: '3.1'
services:
   database:
      image: mysql:5.7
      ports:
         - "3306:3306"
      environment:
         MYSQL_DATABASE: homestead
         MYSQL_USER: homestead
         MYSQL_ROOT_PASSWORD: secret
         MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
